# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uploadimg = QtWidgets.QPushButton(self.centralwidget)
        self.uploadimg.setGeometry(QtCore.QRect(560, 60, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.uploadimg.setFont(font)
        self.uploadimg.setObjectName("uploadimg")
        self.takephoto = QtWidgets.QPushButton(self.centralwidget)
        self.takephoto.setGeometry(QtCore.QRect(670, 60, 91, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.takephoto.setFont(font)
        self.takephoto.setObjectName("takephoto")
        self.imgpath = QtWidgets.QLineEdit(self.centralwidget)
        self.imgpath.setGeometry(QtCore.QRect(560, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.imgpath.setFont(font)
        self.imgpath.setObjectName("imgpath")
        self.probtext = QtWidgets.QLineEdit(self.centralwidget)
        self.probtext.setGeometry(QtCore.QRect(630, 390, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.probtext.setFont(font)
        self.probtext.setObjectName("probtext")
        self.classtext = QtWidgets.QLineEdit(self.centralwidget)
        self.classtext.setGeometry(QtCore.QRect(630, 340, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.classtext.setFont(font)
        self.classtext.setObjectName("classtext")
        self.classify = QtWidgets.QPushButton(self.centralwidget)
        self.classify.setGeometry(QtCore.QRect(560, 230, 301, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.classify.setFont(font)
        self.classify.setObjectName("classify")
        self.imglabel = QtWidgets.QLabel(self.centralwidget)
        self.imglabel.setGeometry(QtCore.QRect(10, 10, 531, 411))
        self.imglabel.setText("")
        self.imglabel.setObjectName("imglabel")
        self.uploadmodel = QtWidgets.QPushButton(self.centralwidget)
        self.uploadmodel.setGeometry(QtCore.QRect(560, 170, 301, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.uploadmodel.setFont(font)
        self.uploadmodel.setObjectName("uploadmodel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(560, 340, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 400, 81, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.havexiaci = QtWidgets.QLineEdit(self.centralwidget)
        self.havexiaci.setGeometry(QtCore.QRect(630, 290, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.havexiaci.setFont(font)
        self.havexiaci.setObjectName("havexiaci")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 290, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 460, 181, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.modelpath = QtWidgets.QLineEdit(self.centralwidget)
        self.modelpath.setGeometry(QtCore.QRect(560, 120, 301, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.modelpath.setFont(font)
        self.modelpath.setObjectName("modelpath")
        self.action1 = QtWidgets.QPushButton(self.centralwidget)
        self.action1.setGeometry(QtCore.QRect(130, 460, 141, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.action1.setFont(font)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QPushButton(self.centralwidget)
        self.action2.setGeometry(QtCore.QRect(300, 460, 141, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.action2.setFont(font)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QPushButton(self.centralwidget)
        self.action3.setGeometry(QtCore.QRect(470, 460, 141, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.action3.setFont(font)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QPushButton(self.centralwidget)
        self.action4.setGeometry(QtCore.QRect(640, 460, 141, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.action4.setFont(font)
        self.action4.setObjectName("action4")
        self.closephoto = QtWidgets.QPushButton(self.centralwidget)
        self.closephoto.setGeometry(QtCore.QRect(770, 60, 91, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(15)
        self.closephoto.setFont(font)
        self.closephoto.setObjectName("closephoto")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uploadimg.setText(_translate("MainWindow", "载入图片"))
        self.takephoto.setText(_translate("MainWindow", "拍摄图片"))
        self.classify.setText(_translate("MainWindow", "分类检测"))
        self.uploadmodel.setText(_translate("MainWindow", "载入模型"))
        self.label.setText(_translate("MainWindow", "类别："))
        self.label_2.setText(_translate("MainWindow", "概率："))
        self.label_3.setText(_translate("MainWindow", "瑕疵："))
        self.label_4.setText(_translate("MainWindow", "机械臂"))
        self.action1.setText(_translate("MainWindow", "连接"))
        self.action2.setText(_translate("MainWindow", "复位"))
        self.action3.setText(_translate("MainWindow", "左移"))
        self.action4.setText(_translate("MainWindow", "右移"))
        self.closephoto.setText(_translate("MainWindow", "关闭拍摄"))
